language: python
group: travis_latest
cache: pip
git:
  depth: 25
  quiet: true

python:
  - "2.7"
  - "3.5"

matrix:
  include:
  - os: linux
    name: PEP8 MyPy Coverage
    python: 3.7
    install:
      - pip install -r requirements.txt
      - python setup.py develop
      - pip install jupyter matplotlib
    script:
      - py.test --cov=pylmeasure tests/
    after_success:
      - codecov
  - os: osx
    language: minimal
    install:
      - pip3 install -r requirements.txt
      - python3 setup.py develop
      - pip3 install jupyter matplotlib
    script:
      - py.test tests/

script:
  - py.test --cov=pylmeasure tests/
