language: python
group: travis_latest
cache: pip
git:
  depth: 25
  quiet: true
matrix:
  include:
  - os: linux
    name: Linux Python 3.7
    python: 3.7
    install:
      - pip install -r requirements.txt
      - python setup.py develop
      - pip install jupyter matplotlib
    script:
      - py.test --cov=pylmeasure tests/
    after_success:
      - codecov
  - os: osx
    language: minimal
    name: OSX Python 3
    install:
      - pip3 install -r requirements.txt
      - python3 setup.py develop
      - pip3 install jupyter matplotlib
    script:
      - py.test tests/

script:
  - py.test --cov=pylmeasure tests/
